version: '3.9'

services:
  db:
    image: postgres:16
    container_name: app-db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: app-backend
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./frontend
    container_name: app-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: always

volumes:
  db-data: