spring:
  datasource:
    url: jdbc:postgresql://db:5432/appdb
    username: appuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /swagger-ui.html